name: list
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number"
        required: true
  issues:
    types: [labeled]
jobs:
  add-deployment:
    name: run commands
    runs-on: ubuntu-latest
    env:
      TEST: hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: list files 
        run: ls -lsa 
      - name: touch test
        run: touch test

        