name: "no list"
on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply the changes"
        required: true
        type: boolean
jobs:
  terraform:
    name: "Terraform"
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        repository: 'test'
      # Checkout the repository to the GitHub Actions runner
      - name: test
        run: date
