name: "no list"
on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply the changes"
        required: true
        type: boolean
      environment:
        description: "Name of the environment"
        type: choice
        required: true
        options:
          - dev
          - qa
          - staging
          - prod
jobs:
  terraform:
    name: "Terraform"
    runs-on: [self-hosted, Linux]
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: test
        run: date
