name: "no list"
on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply the changes"
        required: true
        type: boolean
jobs:
  terraform:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'Uniper-Digital-Trading/dynamic-workflow-options'
          ref: 'main'
      # Checkout the repository to the GitHub Actions runner
      - name: test
        run: date
