name: list
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number"
        required: false
      use_case:
        description: 'Use case'
        type: choice
        required: true
        options:
        - dash-enterprise
        - databricks_ws
        - default
        - genopt
        - gibet
        - gow
        - nordic-dashboard
        - playground
        - ppamgt
        - shared
        - slate

        
  issues:
    types: [labeled]
jobs:
  add-deployment:
    name: Create PR to create use case from issue
    runs-on: ubuntu-latest
    env:
      TEST: hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: touch
        run: free -m; lscpu
      - name: apt
        run: ls -lsa /  
      - name: list files 
        run: ls -lsa 
     
